version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperf_php
    volumes:
      - /Users/sherlock/code/hyperfConfig/app:/var/www/html
      #- /Users/sherlock/code/hyperfConfig/config/php:/etc/php/8.3/cli
    ports:
      - "9501:9501"
      - "9500:9500"
    depends_on:
      - mysql
      - redis
      - nginx
  mysql:
    image: mysql:8
    container_name: hyperf_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/mysql:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hyperf
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: hyperf_redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/redis:/usr/local/etc/redis

  kafka:
    image: bitnami/kafka
    container_name: hyperf_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}  # 监听地址和协议
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "topic_name:1:1"  # 可以在这里设置初始化的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/kafka:/opt/kafka/config:rw


  nginx:
    image: nginx:latest
    container_name: hyperf_nginx
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/nginx:/etc/nginx/conf.d
      - /Users/sherlock/code/hyperfConfig/logs/nginx:/var/log/nginx
    ports:
      - "80:80"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: hyperf_zookeeper
    ports:
      - "2181:2181"
