version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperf_php
    volumes:
      - /Users/sherlock/code/hyperfConfig/app:/var/www
      #- /Users/sherlock/code/hyperfConfig/config/php:/usr/local/etc/php
    ports:
      - "9501:9501"
      - "9500:9500"
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - nginx
  mysql:
    image: mysql:8
    container_name: hyperf_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: hyperf_root_password
      MYSQL_DATABASE: hyperf
      MYSQL_USER: hyperf_guest
      MYSQL_PASSWORD: hyperf_guest_password
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: hyperf_redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/redis:/usr/local/etc/redis

  rabbitmq:
    image: rabbitmq:management
    container_name: hyperf_rabbitmq
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/rabbitmq:/etc/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: hyperf_rabbitmq_user
      RABBITMQ_DEFAULT_PASS: hyperf_rabbitmq_password

#127.0.0.1
  nginx:
    image: nginx:latest
    container_name: hyperf_nginx
    volumes:
      - /Users/sherlock/code/hyperfConfig/config/nginx:/etc/nginx/conf.d
      - /Users/sherlock/code/hyperfConfig/logs/nginx:/var/log/nginx
    ports:
      - "80:80"
